# Machine Learning Notebook

Checkpoint 1
 - [Vader](https://colab.research.google.com/drive/1Jkk4-PBStRz3JNHOEvRDQRXQumBLIrvw#scrollTo=asoIt6yd1s1P&line=2&uniqifier=1)

Checkpoint 2
 - [TextBlob](https://colab.research.google.com/drive/1Jkk4-PBStRz3JNHOEvRDQRXQumBLIrvw#scrollTo=BlTzy8xN6Mu3&line=2&uniqifier=1)

Checkpoint 3
 - [Perspective](https://colab.research.google.com/drive/1Jkk4-PBStRz3JNHOEvRDQRXQumBLIrvw#scrollTo=VETNrn3nef-F&line=2&uniqifier=1)

Checkpoint 4 
- ParalellDots 

## Mount drive, import Data

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
import pandas as pd
path = '/content/drive/My Drive/12-2019-all-hn-data.csv'
# path = 'https://github.com/Build-Week-Saltiest-Hacker-News-1/Machine-Learning/blob/master/12-2019-all-hn-data.csv'
df = pd.read_csv(path)

## Clean Data

In [3]:
df.shape

(10000, 14)

In [4]:
# Set display width to max.
pd.set_option('display.max_colwidth', -1)
df.text.head(5)

0    That&#x27;s basically what trusts are, with a few additional benefits.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             

In [0]:
# Make a df of all the original posts (parents)
parents = df[df.parent.isna()]

In [0]:
import html
# df['clean'] = df.text.apply(html.unescape)

In [0]:
from html.parser import HTMLParser

class HTMLStripper(HTMLParser):
    def __init__(self):
        super().__init__()
        self.reset()
        self.fed = []
    def handle_data(self, d):
        self.fed.append(d)
    def get_data(self):
        return ' '.join(self.fed)
def strip_tags(html):
    s = HTMLStripper()
    s.feed(html)
    return s.get_data()

In [0]:
df['clean'] = df['text'].apply(strip_tags)

In [9]:
df.clean.head(5)

0    That's basically what trusts are, with a few additional benefits.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
1    Huawe

## Sentiment Analysis

- Vader
 - Negativaty
- TextBlob
 - Polarity
- Perspective
 - Toxicity
- ParallelDots
 - Sarcasm

### Vader

In [10]:
!pip install vaderSentiment

     |████████████████████████████████| 133kB 5.2MB/s 


In [0]:
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

vader = SentimentIntensityAnalyzer()

def get_scores(text):
  return vader.polarity_scores(text)

df['scores'] = df.clean.apply(get_scores)

In [12]:
df.scores.head(5)

0    {'neg': 0.0, 'neu': 0.551, 'pos': 0.449, 'compound': 0.6908}  
1    {'neg': 0.088, 'neu': 0.809, 'pos': 0.103, 'compound': 0.216} 
2    {'neg': 0.064, 'neu': 0.776, 'pos': 0.16, 'compound': 0.6652} 
3    {'neg': 0.048, 'neu': 0.835, 'pos': 0.117, 'compound': 0.5095}
4    {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}         
Name: scores, dtype: object

In [0]:
df[['neg', 'neu', 'pos', 'compound']] = df.scores.apply(pd.Series)

In [14]:
for text in df.sort_values(by='neg', ascending=False).text.head(20):
  print(text)

No.
Depressing.
:&#x27;(
Terminal cancer sucks.
No big loss.
Ah sorry I misunderstood
Wrong thread?
What civil war?
<i>Chronicles from a Death Foretold</i><p>Fortunately also a Death Postponed.
yup my bad.
Fuck software patents.
This is stupid
Those poor Sacklers...
Yes. It’s dead.  Killed by money.
Electrocution is literally a fatal electric shock.
<a href="https:&#x2F;&#x2F;en.m.wikipedia.org&#x2F;wiki&#x2F;Gerhard_Schröder" rel="nofollow">https:&#x2F;&#x2F;en.m.wikipedia.org&#x2F;wiki&#x2F;Gerhard_Schröder</a> criticism section
<p><pre><code>  Internal Server Error</code></pre>
<a href="https:&#x2F;&#x2F;www.findagrave.com&#x2F;memorial&#x2F;117717047&#x2F;angus-barbieri" rel="nofollow">https:&#x2F;&#x2F;www.findagrave.com&#x2F;memorial&#x2F;117717047&#x2F;angus-barbieri</a><p>Died age 51.
Just give me what I search for, no filters, no bullshit.
Next to be what? Hacked? Taken over? Become evil?


In [0]:
df.to_csv('/content/drive/My Drive/clean_vader_only.csv', index=False)

#### Checkpoint
-Disconnected? No worries! Start here!

In [0]:
import pandas as pd
#Import csv of Vader processed text
df = pd.read_csv('/content/drive/My Drive/clean_vader_only.csv')

### textBlob

In [18]:
!pip install textblob

In [0]:
from textblob import TextBlob

In [0]:
textblob_sentiment = df['clean'].apply(lambda text: TextBlob(text).sentiment)

In [24]:
textblob_sentiment[0]

Sentiment(polarity=-0.2, subjectivity=0.1)

In [0]:
df[['polarity', 'subjectivity']] = textblob_sentiment.apply(pd.Series)

In [26]:
df.head(1)

Unnamed: 0 title  url  ... compound polarity subjectivity
0  0           NaN  NaN   ...  0.6908  -0.2      0.1        

[1 rows x 23 columns]

In [0]:
df.to_csv('/content/drive/My Drive/clean_vader_tb.csv', index=False)

#### Checkpoint
 - Disconnected? No worries! Start here!

In [0]:
import pandas as pd
# Import csv processed to this point
df = pd.read_csv('/content/drive/My Drive/clean_vader_tb.csv')

### Perspective
- Toxicity

#### API setup

In [0]:
api_key = 'AIzaSyC0286HwADyvmslBz2gIbHOHARkOUynUzI'

In [0]:
url = ('https://commentanalyzer.googleapis.com/v1alpha1/comments:analyze' +    
    '?key=' + api_key)

In [129]:
!gcloud auth login

Go to the following link in your browser:

    https://accounts.google.com/o/oauth2/auth?code_challenge=jCVTA4w7_bLlprb1qrnmp_FKKMYse7KTj4reo7ke1HE&prompt=select_account&code_challenge_method=S256&access_type=offline&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&response_type=code&client_id=32555940559.apps.googleusercontent.com&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fappengine.admin+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcompute+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Faccounts.reauth


Enter verification code: 4/vAGWBXVoHhu8u3ilWMY81mCGjZGRWuFxWSLpDs-M39kM7zEwYb9214o
If you need to use ADC, see:
  gcloud auth application-default --help

You are now logged in as [hakujouryu@gmail.com].
Your current project is [hn-salt-mine].  You can change this setting by running:
  $ gcloud config set project PROJECT_ID


In [130]:
!gcloud config set project hn-salt-mine
!gcloud services enable commentanalyzer.googleapis.com

Updated property [core/project].


In [131]:
import json
import requests

data_dict = {
    'comment': {'text': 'what kind of idiot name is foo?'},
    'languages': ['en'],
    'requestedAttributes': {'TOXICITY': {}}
}
response = requests.post(url=url, data=json.dumps(data_dict)) 
response_dict = json.loads(response.content) 
print(json.dumps(response_dict, indent=2))

{
  "attributeScores": {
    "TOXICITY": {
      "spanScores": [
        {
          "begin": 0,
          "end": 31,
          "score": {
            "value": 0.9208521,
            "type": "PROBABILITY"
          }
        }
      ],
      "summaryScore": {
        "value": 0.9208521,
        "type": "PROBABILITY"
      }
    }
  },
  "languages": [
    "en"
  ],
  "detectedLanguages": [
    "en"
  ]
}


#### Function

In [0]:
import time
import numpy as np

def get_toxicity(comment):
    """ Uses Google's Perspective API to get toxicity."""

    data_dict = {
        'comment': {'text': comment},
        'languages': ['en'],
        'requestedAttributes': {'TOXICITY': {}}
    }
    response = requests.post(url=url, data=json.dumps(data_dict)) 
    response_dict = json.loads(response.content)
    time.sleep(1)
    return response_dict['attributeScores']['TOXICITY']['summaryScore']['value']

##### Testing Function

In [181]:
get_toxicity("I hate you")

0.91280365

In [0]:
test_df = df[df.index < 10]

In [177]:
test_df.head()

Unnamed: 0  Unnamed: 0.1 title  url  ...    pos compound  polarity  subjectivity
0  0           0             NaN  NaN   ...  0.449  0.6908  -0.200000  0.100000    
1  1           1             NaN  NaN   ...  0.103  0.2160   0.116295  0.368899    
2  2           2             NaN  NaN   ...  0.160  0.6652   0.028571  0.766667    
3  3           3             NaN  NaN   ...  0.117  0.5095   0.106944  0.401389    
4  4           4             NaN  NaN   ...  0.000  0.0000   0.000000  0.000000    

[5 rows x 24 columns]

In [0]:
test = [0] * len(test_df)

In [203]:
test

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [204]:
#Set up a for loop this way so that it can be stopped after a while and not loose the data.
test = [0] * len(test_df)
for i in range(len(test_df)):
    print(test[i])
    test[i] = get_toxicity(test_df['clean'][i])
    test_df['toxicity'] = test

0


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.


0
0
0
0
0
0
0
0
0


KeyboardInterrupt: ignored

In [205]:
test

[0.02798886,
 0.27659404,
 0.17991655,
 0.02455593,
 0.12107799,
 0.09185238,
 0.064796604,
 0.100574985,
 0.04940164,
 0]

In [206]:
test_df

Unnamed: 0  Unnamed: 0.1 title  ...  polarity subjectivity  toxicity
0  0           0             NaN   ... -0.200000  0.100000     0.027989
1  1           1             NaN   ...  0.116295  0.368899     0.276594
2  2           2             NaN   ...  0.028571  0.766667     0.179917
3  3           3             NaN   ...  0.106944  0.401389     0.024556
4  4           4             NaN   ...  0.000000  0.000000     0.121078
5  5           5             NaN   ... -0.083333  0.520833     0.091852
6  6           6             NaN   ... -0.075000  0.850000     0.064797
7  7           7             NaN   ...  0.142857  0.517857     0.100575
8  8           8             NaN   ... -0.065000  0.500000     0.049402
9  9           9             NaN   ...  0.030544  0.595578     0.000000

[10 rows x 25 columns]

#### Doing the thing

In [214]:
#Set up a for loop this way so that it can be stopped after a while and not loose the data.
tox_scores = [0] * len(df)
for i in range(len(df)):
    print('Index: ', i)
    tox_scores[i] = get_toxicity(df['clean'][i])
    df['toxic'] = tox_scores
    df.to_csv('/content/drive/My Drive/clean_vader_tb_toxic.csv', index=False)

Index:  0
Index:  1
Index:  2
Index:  3
Index:  4
Index:  5
Index:  6
Index:  7
Index:  8
Index:  9
Index:  10
Index:  11
Index:  12
Index:  13
Index:  14
Index:  15
Index:  16
Index:  17
Index:  18
Index:  19
Index:  20
Index:  21
Index:  22
Index:  23
Index:  24
Index:  25
Index:  26
Index:  27
Index:  28
Index:  29
Index:  30
Index:  31
Index:  32
Index:  33
Index:  34
Index:  35
Index:  36
Index:  37
Index:  38
Index:  39
Index:  40
Index:  41
Index:  42
Index:  43
Index:  44
Index:  45
Index:  46
Index:  47
Index:  48
Index:  49
Index:  50
Index:  51
Index:  52
Index:  53
Index:  54
Index:  55
Index:  56
Index:  57
Index:  58
Index:  59
Index:  60
Index:  61
Index:  62
Index:  63
Index:  64
Index:  65
Index:  66
Index:  67
Index:  68
Index:  69
Index:  70
Index:  71
Index:  72
Index:  73
Index:  74
Index:  75
Index:  76
Index:  77
Index:  78
Index:  79
Index:  80
Index:  81
Index:  82
Index:  83
Index:  84
Index:  85
Index:  86
Index:  87
Index:  88
Index:  89
Index:  90
Index:  9

In [211]:
df.toxic.sort_values(ascending=False).head(5)

1     0.276594
2     0.179917
4     0.121078
10    0.115025
7     0.100575
Name: toxic, dtype: float64

In [212]:
for text in df.sort_values(by='toxic', ascending=False).clean.head(20):
  print(text, '\n')

Huawei had to license synopsys/cadence/mentor to design their chip(which is using ARM core), if US really wants to play hardball Huawei's IC design can be killed nearly instantly once those CAD design software is forbidden. In the meantime I heard Huawei etc bought a few years' license right before the trade war, they're actually well prepared. Another way is to restrict chip manufacturing, Taiwan pretty much owns the best technology for that(TSMC), Intel/Samsung has some, Huawei has none. And you have Android to some degree, without Android there is no Smartphone dominance from China as of now. Open source in general helped China to catch up and overtake the west extremely efficiently, you don't need any business spies anymore, just download/modify/profit. At the moment USA still has the possibility to contain IC ecosystem if it really wants to do that. In 10~20 years it will be a different story though, by then USA might not have much leverage if anything at all left. 

"Bad men need

In [0]:
df.to_csv('/content/drive/My Drive/clean_vader_tb_toxic.csv', index=False)

### ParallelDots

#### Checkpoint
- Disconnected? Start here!

In [0]:
import pandas as pd
# Import csv processed to this point
df = pd.read_csv('/content/drive/My Drive/clean_vader_tb_toxic.csv')

#### API Set-Up

In [0]:
clays_dots_api_key = 'ZxghQ2Ks24ps3U2P2r2TSsmWSFIa5sW1XEvyqsSeQHc'
second_dots_api = 'Toz8zpbQxEAkM1BScN7A0maxxYbHHkAcvIREH6oP7EA'

In [13]:
!pip install paralleldots
import paralleldots

paralleldots.set_api_key(clays_dots_api_key)

#### Testing

In [0]:
sample1 = 'What a great time to drive to the store. Only five billion cars ahead of me.'
response1 = paralleldots.sarcasm(sample1)
print(response1['Sarcastic'])

0.7845338355


In [0]:
text=["I am trying to imagine you with a personality.","I love you.", sample1]
response2 = paralleldots.batch_sarcasm(text)
print(response2)

[{'Non-Sarcastic': 0.3765420414, 'Sarcastic': 0.6234579586}, {'Non-Sarcastic': 0.79160265, 'Sarcastic': 0.20839735}, {'Non-Sarcastic': 0.2154661645, 'Sarcastic': 0.7845338355}]


In [0]:
type(response2)

list

In [0]:
for i, text in enumerate(response2):
  print(f'entry {i+1}: ', text['Sarcastic'])

entry 1:  0.6234579586
entry 2:  0.20839735
entry 3:  0.7845338355


In [0]:
test_list = [num['Sarcastic'] for num in response2]
test_list

[0.6234579586, 0.20839735, 0.7845338355]

#### Working with API

In [0]:
len(list(df.clean))

10000

In [0]:
df.clean.isna().sum()

0

In [0]:
import json


In [25]:
failed = []
for text in df.clean:
    try:
        json.loads(text)
        print(text)
        text = json.loads(text)
        print(text)
    except:
        failed.append(1)

"Hrm. The Wayback Machine has not archived that URL."
Hrm. The Wayback Machine has not archived that URL.
"Currently there is no support for stateful workloads that require persistent volumes or file systems."
Currently there is no support for stateful workloads that require persistent volumes or file systems.
12345
12345
"Oxide is building a new kind of server."
Oxide is building a new kind of server.
"Steve is our best salesman, but he keeps sexually harassing the interns and crashing the company car. Joe janitor just put in his resume..."
Steve is our best salesman, but he keeps sexually harassing the interns and crashing the company car. Joe janitor just put in his resume...
"We could not have imagined, back in 1998 when we moved our servers from a dorm room to a garage, the journey that would follow."
We could not have imagined, back in 1998 when we moved our servers from a dorm room to a garage, the journey that would follow.
"In C I never learned to use the debugger so I used to

In [21]:
len(failed)

9987

In [0]:
df.clean = df.clean.str.strip('"')

In [0]:
df.clean = df.clean.str.strip('<')

In [0]:
df.clean = df.clean.str.strip('>')

In [0]:
df.clean = df.clean.str.strip('')

In [0]:
df.clean = df.clean.str.strip(' ')

In [46]:
df.clean.dtypes

dtype('O')

In [48]:
failed = []
for text in df.clean:
    try:
        json.loads(text)
        print(text)
        text = json.loads(text)
        print(text)
    except:
        failed.append(1)
len(failed)

2009
2009
12345
12345
3
3
1
1


9996

In [0]:
import re

In [0]:
df.clean = df.clean.apply(lambda x: re.sub(r'[^a-zA-Z ^0-9]', '', x))

In [0]:
[re.sub(r'[^a-zA-Z ^0-9]', '', text) for text in df.clean]

In [0]:
this_maybe = list(df.clean)

In [63]:
this_maybe

['Thats basically what trusts are with a few additional benefits',
 'Huawei had to license synopsyscadencementor to design their chipwhich is using ARM core if US really wants to play hardball Huaweis IC design can be killed nearly instantly once those CAD design software is forbidden In the meantime I heard Huawei etc bought a few years license right before the trade war theyre actually well prepared Another way is to restrict chip manufacturing Taiwan pretty much owns the best technology for thatTSMC IntelSamsung has some Huawei has none And you have Android to some degree without Android there is no Smartphone dominance from China as of now Open source in general helped China to catch up and overtake the west extremely efficiently you dont need any business spies anymore just downloadmodifyprofit At the moment USA still has the possibility to contain IC ecosystem if it really wants to do that In 1020 years it will be a different story though by then USA might not have much leverage 

In [0]:
df.to_json('/content/drive/My Drive/comments.JSON')

In [65]:
sarcasm_list = paralleldots.batch_sarcasm( this_maybe )

JSONDecodeError: ignored

In [0]:
sarcasm_list

{'code': 429,
 'message': 'Oops! You have exceeded the rate limit. Please upgrade your plan to get higher rate limits - https://user.apis.paralleldots.com/user_dashboard.'}

## Neural Net
 - Set up a ____ Neural Net 
  - This is because _____

In [0]:
%%capture
def sigmoid(x):
  return 1 / (1 + math.exp(-x))

# Normalize polarity vals between 0 and 1.
scores.polarity = scores.polarity.apply(sigmoid)

In [0]:
%%capture
# Create salt metric:
# Sum of negativity, subjectivity, and toxicity. Subtract polarity.
# Apply sigmoid function to that sum.

scores['salt'] = scores[['neg', 'subjectivity', 'toxic']].sum(axis=1)
scores.salt = scores.salt - scores.polarity
scores.salt = scores.salt.apply(sigmoid)

In [0]:
# Add saltiness metric to df.
df['salt'] = scores['salt']

In [0]:
train, test = train_test_split(df)

X_train = train.clean
y_train = train.salt
X_test = test.clean
y_test = test.salt

In [0]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()

X_train = vectorizer.fit_transform(X_train)
X_test = vectorizer.transform(X_test)

In [0]:
X_train.shape, X_test.shape

((7500, 26480), (2500, 26480))

In [0]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, LSTM

model = Sequential([
    Dense(128, input_dim=26480, activation='relu'),
    Dropout(0.2),
    Dense(128, activation='relu'),
    Dropout(0.2),
    # LSTM(128, activation='relu'),
    # Dropout(0.2),
    Dense(32, activation='relu'),
    Dropout(0.2),
    Dense(16, activation='relu'),
    Dropout(0.2),
    Dense(1, activation='sigmoid')
])

model.compile(
    loss='mae',
    optimizer='adam',
    metrics=['mae']
)

Instructions for updating:
If using Keras pass *_constraint arguments to layers.


In [0]:
%%time
fitted = model.fit(X_train, y_train, batch_size=64, epochs=100, validation_split=.1, verbose=1)
scores = model.evaluate(X_test, y_test)
print(f'{model.metrics_names[1]}: {scores[1]*100}')

Train on 6750 samples, validate on 750 samples
Epoch 1/100
6750/6750 [==============================] - 3s 431us/sample - loss: 0.0532 - mean_absolute_error: 0.0532 - val_loss: 0.0466 - val_mean_absolute_error: 0.0466
Epoch 2/100
6750/6750 [==============================] - 1s 184us/sample - loss: 0.0411 - mean_absolute_error: 0.0411 - val_loss: 0.0429 - val_mean_absolute_error: 0.0429
Epoch 3/100
6750/6750 [==============================] - 1s 173us/sample - loss: 0.0333 - mean_absolute_error: 0.0333 - val_loss: 0.0415 - val_mean_absolute_error: 0.0415
Epoch 4/100
6750/6750 [==============================] - 1s 182us/sample - loss: 0.0277 - mean_absolute_error: 0.0277 - val_loss: 0.0412 - val_mean_absolute_error: 0.0412
Epoch 5/100
6750/6750 [==============================] - 1s 162us/sample - loss: 0.0243 - mean_absolute_error: 0.0243 - val_loss: 0.0414 - val_mean_absolute_error: 0.0414
Epoch 6/100
6750/6750 [==============================] - 1s 183us/sample - loss: 0.0222 - mean_abs

In [0]:
sample = ['I love driving to work. It is fun being stuck in traffic watching my life waste away.']
model.predict(vectorizer.transform(sample))

array([[0.53049564]], dtype=float32)

In [0]:
sample2 = ['you are the best']
model.predict(vectorizer.transform(sample2))

array([[0.4772234]], dtype=float32)

In [0]:
sample3 = ['I appreciate you']
model.predict(vectorizer.transform(sample3))

array([[0.40309933]], dtype=float32)

In [0]:
sample4 = ['How is that wrong? Clearly anyone who says that is being somewhat facetious / comedic.']
model.predict(vectorizer.transform(sample4))

array([[0.68447244]], dtype=float32)

In [0]:
sample5 = ['Thanks for the context. Thought that this was contemporary. The language did seem antiquated.']
model.predict(vectorizer.transform(sample5))

array([[0.45324525]], dtype=float32)

#### Save Models

In [0]:
# model.save_weights('baseline_nn2.h5')
model.save('baseline_model.h5')

In [0]:
import pickle
pickle.dump(vectorizer, open("tfidf.pickle", "wb"))

In [0]:
vectorizer2 = pickle.load(open("tfidf.pickle", "rb"))

In [0]:
# from tensorflow.keras.models import load_model

new_model = load_model('baseline_model.h5')

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


#### OLD


In [0]:
df[df.toxic > .50][df.neg > .2]

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.


Empty DataFrame
Columns: [title, url, text, dead, by, score, time, timestamp, type, id, parent, descendants, ranking, deleted, clean, scores, neg, neu, pos, compound, toxic]
Index: []

In [0]:
toxic_df = df[df['toxic'].isna() == False]

In [0]:
toxic_df.neg.sort_values(ascending=False)

10    0.423
26    0.370
14    0.369
7     0.271
19    0.237
      ...  
43    0.000
40    0.000
39    0.000
38    0.000
0     0.000
Name: neg, Length: 100, dtype: float64

In [0]:
toxic_df[toxic_df.neg > .2]

title  url  ... compound     toxic
7   NaN  NaN   ...  0.0000   0.100575
10  NaN  NaN   ... -0.7650   0.115025
14  NaN  NaN   ... -0.8591   0.195372
19  NaN  NaN   ... -0.4767   0.221195
26  NaN  NaN   ... -0.9530   0.112086

[5 rows x 21 columns]